name: movie_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.1
  skeletonizer: ^2.1.3
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash_screen/splash_ios_android_11.png"
  adaptive_icon_background: "#5F33E1"
  adaptive_icon_foreground: "assets/icons/app_icon/play-store-icon-launcher.png"
